/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"address.add": "User can add / modify / delete an address",
};

export default permissions;
